### PR TITLE
[DO NOT MERGE] ENH: Converted all PNGs to JPGs

### PR DESCRIPTION
**Pull request by AntoineTheb**
To save some space on the repo, and since we often use images in our reviews, I converted all PNGs to JPGs and updated the links in the articles.

Commands used (from the root of the repo):
```
# Recursively find all PNGs and convert them to JPGs using imagemagick
# Change the extension from ".png" to ".jpg"
$ find . -type f | while read IN; do   
    if [ "x$(file -b --mime-type $IN)" = "ximage/png" ]; then     
        convert png:$IN jpg:${IN::-4}.jpg; rm $IN;   
    fi; 
  done;

# Delete all PNGs
$ find . -name "*.png" -type f -delete

# Find and replace every occurence of "png" by "jpg" in markdown files
$ find ./ -type f -iname "*.md" -exec sed -i 's/png/jpg/g' "{}" +;

# Rewrite history to remove PNGs
$ wget http://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar
$ java -jar bfg-1.13.0.jar --delete-files *.{png} ./;

# Commit and pray to the Git Gods 
$ git reflog expire --expire=now --all && git gc --prune=now --aggressive
$ git push --force

```

### CODE REVIEW

**Comment by lemairecarl** [comment]
The PNGs will remain in the history, unless we perform some kind of trick.

**Comment by AntoineTheb** [comment]
Then we have to do that trick also

**Comment by lemairecarl** [comment]
This might be helpful (the links in the post also)
https://stackoverflow.com/questions/17418514/remove-all-binary-files-recursively-from-git-repo-and-commit-history/17419097

**Comment by jhlegarreta** [comment]
Will we dare to apply the solution directly or shall we create a temporary repository with a few commits and images to test the approach?

**Comment by AntoineTheb** [comment]
I'll make a local copy of the repo in the state of this current branch and test the changes. I'll report back on the results.

**Comment by AntoineTheb** [comment]
I used BFG (https://rtyley.github.io/bfg-repo-cleaner/) to rewrite the repo's history and the repo's size went from 514 mb to 174mb, which is nice. BFG was super easy to use and was really fast, too. I have updated the script in the first comment to include the history's rewrite.

**Comment by jhlegarreta** [comment]
Awesome. :+1: for applying the change to the repository. GitHub sees some conflicts; not sure what the conflicts are.

Thanks for doing things.

**Comment by AntoineTheb** [comment]
@jhlegarreta

All the conflicts are because the history has been rewritten, so this current PR has a a different history than the master branch for the same files. Reading more on the subject, after using `git-filter-branch` to do the kind of procedure done here in this branch (such as deleting large binaries or unused files), the usual procedure is to make a clone of the repo with the re-written history.

I am now not really sure we should go ahead with this, as I am not sure that it is worth the effort of having everyone switch to another repo, even if it's a clone of this one.

@lemairecarl what do you think ?

**Comment by lemairecarl** [comment]
1. Right now, the total size of the repo on my disk (history included) is 1.1GB. Is it because of this branch which contains a lot of stuff? Do you know the size the history will have after the changes?
2. Comparing the `article` folder before/after your changes: I see savings of 119MB, which is not that significant in the long term. Am I looking at the right number?
2. The hard limit on repo size is 100GB, although Github support will send an email if we exceed 1GB. My interpretation is that history is included in the size. https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota
3. Please populate this repo https://github.com/vitalab/vitalab-dot-jpg with the new version, so we can test it. We could also invite everybody, and eventually swap the two repos.

**Comment by AntoineTheb** [comment]
1-2. Checking out a fresh version of the repo,`master` is only 315.6mb, and when checking out this branch, it goes down to 192.1mb on my end. The whole GB might be from old branches that have been deleted on `origin` ?

3. The hard limit on published Github pages is 1GB, so if we can push back the day the repo hits it I think we should
https://help.github.com/en/github/working-with-github-pages/about-github-pages#guidelines-for-using-github-pages
4.

**Comment by jhlegarreta** [comment]
@lemairecarl Assuming your `origin` points to the remote repository, can you do
```git remote prune origin
```
and see if the size of the repository in your local disk decreases?

**Comment by AntoineTheb** [comment]
So I tried to fork the repo, squash everything and then make a pull request. However, Github doesn't like that:
image

I guess we'll have to go the hard way: Make the changes we want (delete all pngs, etc.), delete the .git folder to erase history and then reinit the repo and force-push everything back. This does mean we would lose all the settings of the repo. If @lemairecarl makes me an admin I could do it.

**Comment by jhlegarreta** [comment]
Thanks for the effort @AntoineTheb . IMHO, the history of this repository is not something we would need to re-visit, so I'd in favour of the solution you proposed.

**Comment by lemairecarl** [comment]
Sorry, I missed the notification.

You are now an pwner.

Go ahead!

**Comment by AntoineTheb** [comment]
Time flies by, huh ? 

Closing this, we haven't run out of space yet. We'll see down the line how it goes.

**Comment by lemairecarl** [comment]
I just converted the pngs from an old post, and I was surprised to see that the jpgs take more space:

```
carl@carl-laptop:~/web/vitalab.github.io/article/images/contrastiveLoss$ du --total *.jpg
17	sc01.jpg
37	sc02.jpg
25	sc03.jpg
13	sc04.jpg
361	sc05.jpg
13	sc06.jpg
13	sc07.jpg
476	total
carl@carl-laptop:~/web/vitalab.github.io/article/images/contrastiveLoss$ du --total *.png
13	sc01.png
25	sc02.png
17	sc03.png
9	sc04.png
301	sc05.png
13	sc06.png
13	sc07.png
388	total
```

That's not a big difference, but if we ever need to batch convert all the images, we'll have to lower the quality of the jpgs. Or replace the png only of the jpg is smaller... Let's hope we won't have to come back to this! haha

**Pull request closed without merging**
