### PR TITLE
ENH: Add `Gemfile.lock` to `.gitignore`.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add the Ruby `Gemfile.lock` to the ignore files in `.gitignore`.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
I guess those who run the local server have a modified version of this file at some point (may be if their Ruby version is different). Adding it to the `.gitignore` file list may be a solution to avoid accidentally including it to our commits.

**Comment by AntoineTheb** [comment]
`gemfile.lock` acts like `yarn.lock` for yarn of `package-lock.json` for npm. It specifies which version of your dependencies the project uses.

https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files

Most people seem to advocate for keeping the `gemfile.lock` in the vcs.

**Comment by jhlegarreta** [comment]
Thanks @AntoineTheb  !

I see the point. Looks reasonable. So may be the change we should make is on [this section](https://github.com/vitalab/vitalab.github.io/blob/master/how-to-install-ruby.md#install-ruby) of the 
 `how-to-install-ruby.md` file: the comment in the instruction
```
rbenv install -v 2.4.0  # Replace by the latest version of Ruby
```
was the one that led me to look for and install the latest version of Ruby, which is `2.6.0` right now.

@lemairecarl if you agree, I'll submit a PR removing that comment, and will close this PR.

**Comment by lemairecarl** [comment]
Nooooo... not this again... :(

It happened multiple times that we had a game of ping pong between two people, committing their own different gemfile.lock, because they didn't know that it was related to Ruby packages' version. I wish there was a simple solution to avoid this... it seems there isn't (unless we all have the same version of all packages).

I really don't know what we should do.

**Comment by jhlegarreta** [comment]
Thanks for sharing your viewpoint @lemairecarl.

On the one hand, if we are all to share the same local settings/installation, the notice of installing the latest version of the Ruby environment should be removed from the referred markdown file. **I will follow with a patch for that**.

On the other hand, best would be to use the `Gemfile.lock` file to install the environment, much like one does with a `requirements.txt` file for a Python environment, if that makes sense or if it is at all possible. So we'd need to find the way to tell Ruby to take those versions (?). We'll need to do some research to know how to do so.

And finally, once that done, as @AntoineTheb suggested, keeping the `Gemfile.lock` in the repository, and continuing to track it seems fair. Any change to that file should be due to security issues or other vulnerabilities announced by the Ruby community.

**Comment by lemairecarl** [comment]
I merged #324.

We'll try to keep an official Ruby version for the lab, and modify the HOWTO when it changes. For now it will be 2.4.0. Since our site is static, there are no security concerns to have.

So when somebody will try to merge their `gemfile.lock` (it will happen -- Murphy's law), we'll just have to catch it _before it's too late_.

**Comment by jhlegarreta** [comment]
Merci Carl.

**Pull request closed without merging**
