### PR TITLE
ENH/FIX: Remove unused fonts

### PR DESCRIPTION
**Pull request by AntoineTheb**
I snuck the last PRs to fix the math rendering problems ASAP, but this one is not urgent. This is just to remove (I think) unused files. Let me know if it breaks anything

### CODE REVIEW

**Comment by nathanpainchaud** [comment]
I tested it locally on 2 of my reviews that are quite math-heavy, and nothing seems broken as far as I'm concerned.

However, since the sneaky PR and the non-local KaTeX, the local folders created by Jekyll to cache data are different. So I would propose [an update to the `.gitignore` file](https://github.com/vitalab/vitalab.github.io/files/5081363/gitignore.txt), where I deleted some entries (that never appeared on my system anyway) and added the new cache directory.

**Comment by AntoineTheb** [comment]
@nathanpainchaud @jhlegarreta 
Indeed, I have simply added `.jekyll-cache` to the .gitignore and kept everything else in d89c482

**Comment by nathanpainchaud** [comment]
> @nathanpainchaud @jhlegarreta
> Indeed, I have simply added `.jekyll-cache` to the .gitignore and kept everything else in [d89c482](https://github.com/vitalab/vitalab.github.io/commit/d89c4820f544791fa2d66c60808752ace51676b3)

You made your point pretty eloquently @jhlegarreta :wink: @AntoineTheb Seems good to me. LGTM!

**Comment by jhlegarreta** [comment]
@AntoineTheb @nathanpainchaud  thanks both for having taken care of this !

**Comment by lemairecarl** [comment]
You guys are a bunch of gentlemen, you know that?

**Pull request merged**
