### PR TITLE
ENH: Refactor categories

### LINKED ISSUE #311: Refactor categories?
Categories and tags have overlapping functionality... I guess we could use categories to determine the type of review, e.g.: Article review, Online course review, tutorial, tips & tricks, etc. Then, we would handle the rest with tags (domain, type of method, type of data, etc...)

(Not a critical issue)

### PR DESCRIPTION
**Pull request by jhlegarreta**
Refactor categories:
- Move all review posts (i.e. folders `deep-learning`,
  `machine-learning`, `medical-imaging`, `pruning-acceleration`,
  `reinforcement-learning`, and `video-analysis`) to a new `article`
  folder.
- Add the appropriate tags to files that were missing descriptive tags
  from the ancient categories/folders.

Add the script used to refactor the categories to a new folder called
`utilities`.

Fixes #311.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Following #350 .

Side effect: acronyms in the tag list have also been ordered alphabetically. I guess we can live with that.

**Comment by jhlegarreta** [comment]
Well, looks like @lemairecarl and I identified a few corner cases that have gone unhandled.

A simple
```
find article/_posts/ -name '*.md' -exec grep -e "/deep-learning" {} \; -print
```

finds a few corner cases that I have not considered.

We could fix them manually, but that would mean that the script cannot be re-used if at some point another refactoring needs to be done (with a few changes to the listed categories, etc.).

So the cases that need to be handled:
- A reference to an image has a **named reference**: e.g. `Xception architecture`
- Two images are in the **same line**:  e.g. `
`
- A reference to an image is **preceded by other characters**: e.g. `|    |    |`
- Cross references to **articles**: e.g. `This paper proposes a segmentic segmentation method which is a combination of a [U-Net](https://vitalab.github.io/deep-learning/2017/02/27/unet.html)` or `somehow similar in spirit to [ACNN](https://vitalab.github.io/deep-learning/2018/05/30/ACNN.html).` or `[PointNet](https://vitalab.github.io/deep-learning/2018/12/20/pointnet.html),`
- Some other cases that **apparently should have been handled**: e.g. `> ` or ``.

And there may be other for the ancient categories (i.e. `machine-learning`, `medical-imaging`, etc.).

So another iteration will be needed to handle this in the script.

**Comment by lemairecarl** [comment]
I also have seen multiple cases of:
`tags: "Deep Learning" deep-learning`
or similar. Not sure how that happened. There seem to originally be many articles with errors the yaml header

**Comment by jhlegarreta** [comment]
I think I have seen some of those where the original tags where not the ones expected/listed/not according to the convention, but given that the purpose of this script was another one, I simply did not want to treat them in here. I guess that if a tag does not exist in the `tags.yml` file, no tags are added to it.

Now, what we could do is to **add another script** to `utilities` that we could use from time to time to **check if the tags used in the article reviews contain no tags other than the ones in `tags.yml`**, and if they do: 
- It is an incorrect tag, like the above, and we should change it for the correct one
- It is a tag that does make sense/is correct, but does not exist, add it to the file.

But may need to be done manually asking for each.

**Comment by jhlegarreta** [comment]
Having said that, and according to @lemairecarl 's local tests with this PR, Jekyll will have trouble in building the site if cases like `tags: "Deep Learning" deep-learning` are not treated.

So I'd dare to say that the *second* script will be a requirement before running the category refactoring one.

**Comment by jhlegarreta** [comment]
f7a6376 addressed the review cross-references.

**Comment by jhlegarreta** [comment]
So except for the tags double quote issue, I'd dare to say that the rest of the issues have been addressed.

**Comment by jhlegarreta** [comment]
Well, looks like some cross-references were still missing because the `sed` statements were only modifying the first match found on the same line.

743dd40 fixes that.

**Comment by lemairecarl** [comment]
I've look at quite a few articles, and they were all good. Great work!

Merge this when you're ready!

**Comment by lemairecarl** [comment]
I have covered the case of tags inside quotes here: #357

**Pull request closed without merging**
