### PR TITLE
Associative Compression Networks

### PR DESCRIPTION
**Pull request by nathanpainchaud**

### CODE REVIEW

**Comment by nathanpainchaud** [comment]
Quick question, but should I have taken the screenshots as jpegs? Or are we gonna change only once we have pushed the converted repo?

**Comment by AntoineTheb** [comment]
Doesn't really matter for this commit but it could be a good habit to start saving screenshots as jpegs onward

**Comment by jhlegarreta** [comment]
> Doesn't really matter for this commit but it could be a good habit to start saving screenshots as jpegs onward

Unless there is a bug that went unnoticed, if you installed the pre-commit hooks, they should have detected that you were trying to commit PNG images and should have prevent the commit.

**Comment by nathanpainchaud** [comment]
> Unless there is a bug that went unnoticed, if you installed the pre-commit hooks, they should have detected that you were trying to commit PNG images and should have prevent the commit.

I thought I had installed the pre-commit hooks, but maybe I messed up the installation somewhere. As Antoine said, I don't think it matters for now, but I'll make sure they're active so that this doesn't happen in the future.

**Comment by jhlegarreta** [comment]
> I thought I had installed the pre-commit hooks, but maybe I messed up the installation somewhere.

May be you installed them before the PNG detection was brought to the hook? This is [relatively recent](https://github.com/vitalab/vitalab.github.io/pull/438). Open an issue :bug: if they do not do their job.

**Pull request merged**
